declare module "*.png";
declare module "*.jpg";
declare module "*.webp";
declare module "*.svg";
declare module "numeral";
declare module "react-slick";
declare module "styled-components";
declare module "react-scroll";
declare module "react-share";
